# Generated by Django 3.0.7 on 2020-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTaxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.IntegerField(unique=True)),
                ('data', models.CharField(max_length=1000)),
                ('denumire', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=1000)),
                ('scpTVA', models.BooleanField()),
                ('data_inceput_ScpTVA', models.CharField(max_length=1000)),
                ('data_sfarsit_ScpTVA', models.CharField(max_length=1000)),
                ('data_anul_imp_ScpTVA', models.CharField(max_length=1000)),
                ('mesaj_ScpTVA', models.CharField(max_length=1000)),
                ('dataInceputTvaInc', models.CharField(max_length=1000)),
                ('dataSfarsitTvaInc', models.CharField(max_length=1000)),
                ('dataActualizareTvaInc', models.CharField(max_length=1000)),
                ('dataPublicareTvaInc', models.CharField(max_length=1000)),
                ('tipActTvaInc', models.CharField(max_length=1000)),
                ('statusTvaIncasare', models.BooleanField()),
                ('dataInactivare', models.CharField(max_length=1000)),
                ('dataReactivare', models.CharField(max_length=1000)),
                ('dataPublicare', models.CharField(max_length=1000)),
                ('dataRadiere', models.CharField(max_length=1000)),
                ('statusInactivi', models.BooleanField()),
                ('dataInceputSplitTVA', models.CharField(max_length=1000)),
                ('dataAnulareSplitTVA', models.CharField(max_length=1000)),
                ('statusSplitTVA', models.BooleanField()),
                ('iban', models.CharField(max_length=100)),
            ],
        ),
    ]
