# Generated by Django 3.0.7 on 2020-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxreader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytaxinfo',
            name='scpTVA',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='companytaxinfo',
            name='statusInactivi',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='companytaxinfo',
            name='statusSplitTVA',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='companytaxinfo',
            name='statusTvaIncasare',
            field=models.BooleanField(null=True),
        ),
    ]
