# Generated by Django 3.0.7 on 2020-06-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxreader', '0003_responsefromanaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsefromanaf',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
