# Generated by Django 3.0.7 on 2020-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxreader', '0004_auto_20200622_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytaxinfo',
            name='cui',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='companytaxinfo',
            unique_together={('cui', 'data')},
        ),
    ]
